language: ruby
sudo: false
cache: bundler

matrix:
  include:
    - rvm: 2.0
      env: COMMAND=rspec
    - rvm: 2.1
      env: COMMAND=rspec
    - rvm: 2.2
      env: COMMAND=rspec
    - rvm: jruby
      env: COMMAND=rspec
    - rvm: 2.2
      env: COMMAND=rubocop
  allow_failures:
    - rvm: 2.2
      env: COMMAND=rubocop

before_install: gem install bundler -v 1.10.6
script: bundle exec $COMMAND
